### ISSUE TITLE
Instillation by pip fails

### ISSUE THREAD

**Issue by JKvet** [SciKit-Surgery/scikit-surgerynditracker#81]
This is due to a /s in the versioner file within a string starting on line 421. The following error message occurs on install

Collecting scikit-surgerynditracker
  Using cached scikit-surgerynditracker-1.0.0.tar.gz (24 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      /private/var/folders/v2/sxdpv_c51rz_kn1xgrmf2z_w0000gn/T/pip-install-jy93u0vl/scikit-surgerynditracker_9f904707926d43d39b44cbb09fea6fe6/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/v2/sxdpv_c51rz_kn1xgrmf2z_w0000gn/T/pip-build-env-oz_f4zv4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/v2/sxdpv_c51rz_kn1xgrmf2z_w0000gn/T/pip-build-env-oz_f4zv4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/v2/sxdpv_c51rz_kn1xgrmf2z_w0000gn/T/pip-build-env-oz_f4zv4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/v2/sxdpv_c51rz_kn1xgrmf2z_w0000gn/T/pip-build-env-oz_f4zv4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 15, in <module>
        File "/private/var/folders/v2/sxdpv_c51rz_kn1xgrmf2z_w0000gn/T/pip-install-jy93u0vl/scikit-surgerynditracker_9f904707926d43d39b44cbb09fea6fe6/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/v2/sxdpv_c51rz_kn1xgrmf2z_w0000gn/T/pip-install-jy93u0vl/scikit-surgerynditracker_9f904707926d43d39b44cbb09fea6fe6/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/v2/sxdpv_c51rz_kn1xgrmf2z_w0000gn/T/pip-install-jy93u0vl/scikit-surgerynditracker_9f904707926d43d39b44cbb09fea6fe6/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by thompson318** [comment]
Thanks for raising this. This looks like an issue with Python 3.12 and our versioning code (https://github.com/python-versioneer/python-versioneer). I'll try and have a look at fixing it this week. If you're in a hurry the quickest fix for you might be to use an earlier version of Python.

**Comment by thompson318** [comment]
@JKvet I think this is fixed now. Please can you try again with python 3.12. You need to make sure your using version 1.0.1, which may involve clearing your pip cache. If it works please let me know and we can close the issue.

**Comment by JKvet** [comment]
Thank you yes this now successfully downloads
